import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Navigation from './navigation'

const roboto = Roboto({ weight: '300', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
